import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, TrendingDown, Coins, AlertCircle, Star, } from "lucide-react";
import { Link } from "react-router-dom";
const MostExpensiveCryptos = ({ loading, expensiveCoins, error, }) => {
    const formatPrice = (price) => {
        return new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
            minimumFractionDigits: 0,
            maximumFractionDigits: 2,
        }).format(price);
    };
    const formatPercentage = (percentage) => {
        return `${percentage >= 0 ? "+" : ""}${percentage.toFixed(2)}%`;
    };
    // Loading skeleton component
    const LoadingSkeleton = () => (_jsxs("div", { className: "p-6 bg-white border border-gray-100 shadow-xl rounded-2xl animate-pulse", children: [_jsxs("div", { className: "flex items-center mb-4 space-x-4", children: [_jsx("div", { className: "bg-gray-200 rounded-full h-14 w-14" }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("div", { className: "w-24 h-4 bg-gray-200 rounded" }), _jsx("div", { className: "w-16 h-3 bg-gray-200 rounded" })] }), _jsx("div", { className: "w-6 h-6 bg-gray-200 rounded-full" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "w-32 h-8 bg-gray-200 rounded" }), _jsx("div", { className: "w-20 h-5 bg-gray-200 rounded" })] })] }));
    if (loading) {
        return (_jsx("section", { className: "min-h-screen py-20 bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50", children: _jsxs("div", { className: "container px-4 mx-auto sm:px-6 lg:px-8", children: [_jsxs("div", { className: "mb-16 text-center", children: [_jsx("div", { className: "inline-flex items-center justify-center w-16 h-16 mx-auto mb-6 bg-indigo-100 rounded-full animate-pulse", children: _jsx(Coins, { className: "w-8 h-8 text-indigo-600" }) }), _jsx("div", { className: "h-12 mx-auto mb-4 bg-gray-200 rounded-lg w-96 animate-pulse" }), _jsx("div", { className: "w-64 h-6 mx-auto bg-gray-200 rounded animate-pulse" })] }), _jsx("div", { className: "grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4", children: Array.from({ length: 8 }).map((_, index) => (_jsx(LoadingSkeleton, {}, index))) })] }) }));
    }
    if (error) {
        return (_jsx("section", { className: "flex items-center justify-center min-h-screen py-20 bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50", children: _jsx("div", { className: "container px-4 mx-auto sm:px-6 lg:px-8", children: _jsxs("div", { className: "max-w-md mx-auto text-center", children: [_jsx("div", { className: "inline-flex items-center justify-center w-16 h-16 mb-6 bg-red-100 rounded-full", children: _jsx(AlertCircle, { className: "w-8 h-8 text-red-600" }) }), _jsxs("div", { className: "p-8 bg-white border border-red-100 shadow-xl rounded-2xl", children: [_jsx("h3", { className: "mb-2 text-xl font-semibold text-gray-900", children: "Connection Error" }), _jsx("p", { className: "mb-4 text-gray-600", children: error }), _jsx("button", { onClick: () => window.location.reload(), className: "inline-flex items-center px-4 py-2 text-white transition-colors bg-red-600 rounded-lg hover:bg-red-700", children: "Try Again" })] })] }) }) }));
    }
    return (_jsx("section", { id: "expensive", className: "min-h-screen py-20 bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50", children: _jsxs("div", { className: "container px-4 mx-auto sm:px-6 lg:px-8", children: [_jsxs("div", { className: "mb-16 text-center", children: [_jsx("div", { className: "inline-flex items-center justify-center w-16 h-16 mb-6 rounded-full shadow-lg bg-gradient-to-br from-indigo-500 to-purple-600", children: _jsx(Coins, { className: "w-8 h-8 text-white" }) }), _jsx("h2", { className: "mb-4 text-5xl font-bold text-transparent sm:text-6xl bg-gradient-to-r from-indigo-600 via-purple-600 to-blue-600 bg-clip-text", children: "Premium Cryptocurrencies" }), _jsx("p", { className: "max-w-3xl mx-auto text-xl leading-relaxed text-gray-600", children: "Discover the most valuable digital assets in today's market with real-time pricing and performance metrics." })] }), _jsx("div", { className: "grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4", children: expensiveCoins.map((crypto, index) => (_jsxs(Link, { to: `/coins/${crypto.name}`, className: "relative overflow-hidden transition-all duration-500 bg-white border border-gray-100 shadow-xl cursor-pointer group rounded-2xl hover:shadow-2xl hover:-translate-y-2 backdrop-blur-sm", children: [index < 3 && (_jsx("div", { className: "absolute z-10 top-4 right-4", children: _jsx("div", { className: `flex items-center justify-center w-8 h-8 rounded-full text-white text-sm font-bold shadow-lg ${index === 0
                                        ? "bg-gradient-to-r from-yellow-400 to-orange-500"
                                        : index === 1
                                            ? "bg-gradient-to-r from-gray-400 to-gray-600"
                                            : "bg-gradient-to-r from-orange-400 to-red-500"}`, children: index + 1 }) })), _jsx("div", { className: "absolute inset-0 transition-opacity duration-500 opacity-0 bg-gradient-to-br from-indigo-50 to-purple-50 group-hover:opacity-100" }), _jsxs("div", { className: "relative p-6", children: [_jsxs("div", { className: "flex items-center mb-6 space-x-4", children: [_jsx("div", { className: "relative", children: _jsx("div", { className: "flex items-center justify-center overflow-hidden rounded-full shadow-lg w-14 h-14 bg-gradient-to-br from-indigo-100 to-purple-100 ring-2 ring-white", children: _jsx("img", { src: crypto.image, alt: crypto.name, className: "object-cover w-10 h-10 transition-transform duration-300 rounded-full group-hover:scale-110", onError: (e) => {
                                                            const target = e.target;
                                                            target.style.display = "none";
                                                        } }) }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "text-lg font-bold text-gray-900 truncate transition-colors group-hover:text-indigo-600", children: crypto.name }), _jsx("p", { className: "text-sm tracking-wider text-gray-500 uppercase truncate", children: crypto.symbol || "CRYPTO" })] }), _jsx(Star, { className: "w-5 h-5 text-gray-300 transition-colors group-hover:text-yellow-400" })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("div", { children: _jsx("p", { className: "mb-1 text-3xl font-bold text-gray-900", children: formatPrice(crypto.current_price) }) }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-medium text-gray-500", children: "24h Change" }), _jsxs("div", { className: `flex items-center space-x-2 px-3 py-1.5 rounded-full font-semibold text-sm ${crypto.price_change_percentage_24h >= 0
                                                            ? "text-emerald-700 bg-emerald-50 border border-emerald-200"
                                                            : "text-red-700 bg-red-50 border border-red-200"}`, children: [crypto.price_change_percentage_24h >= 0 ? (_jsx(TrendingUp, { className: "w-4 h-4" })) : (_jsx(TrendingDown, { className: "w-4 h-4" })), _jsx("span", { children: formatPercentage(crypto.price_change_percentage_24h) })] })] }), crypto.market_cap && (_jsx("div", { className: "pt-4 border-t border-gray-100", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm font-medium text-gray-500", children: "Market Cap" }), _jsx("span", { className: "text-sm font-semibold text-gray-700", children: formatPrice(crypto.market_cap) })] }) }))] })] }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 transition-transform duration-500 origin-left transform scale-x-0 bg-gradient-to-r from-indigo-500 via-purple-500 to-blue-500 group-hover:scale-x-100" })] }, index))) }), expensiveCoins.length === 0 && !loading && (_jsxs("div", { className: "py-16 text-center", children: [_jsx("div", { className: "inline-flex items-center justify-center w-20 h-20 mb-6 bg-gray-100 rounded-full", children: _jsx(Coins, { className: "w-10 h-10 text-gray-400" }) }), _jsx("h3", { className: "mb-3 text-2xl font-semibold text-gray-900", children: "No cryptocurrencies found" }), _jsx("p", { className: "max-w-md mx-auto text-lg text-gray-600", children: "Unable to load cryptocurrency data at this time. Please check your connection and try again." })] })), expensiveCoins.length > 0 && (_jsx("div", { className: "mt-16 text-center", children: _jsxs("div", { className: "inline-flex items-center px-8 py-4 space-x-8 bg-white border border-gray-100 shadow-lg rounded-2xl", children: [_jsxs("div", { children: [_jsx("p", { className: "text-2xl font-bold text-indigo-600", children: expensiveCoins.length }), _jsx("p", { className: "text-sm font-medium text-gray-600", children: "Premium Assets" })] }), _jsx("div", { className: "w-px h-8 bg-gray-200" }), _jsxs("div", { children: [_jsx("p", { className: "text-2xl font-bold text-purple-600", children: "Live" }), _jsx("p", { className: "text-sm font-medium text-gray-600", children: "Market Data" })] })] }) }))] }) }));
};
export default MostExpensiveCryptos;
