import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardHeader } from "../../components/ui/card";
import { Badge } from "../../components/ui/badge";
import { Skeleton } from "../../components/ui/skeleton";
import { Alert, AlertDescription } from "../../components/ui/alert";
import { TrendingUp, TrendingDown, ArrowUpRight, ArrowDownRight, Sparkles, RefreshCw, } from "lucide-react";
import { Link } from "react-router-dom";
const TrendingCryptos = ({ trendingCoins, loading, error, }) => {
    const formatPrice = (price) => {
        return new Intl.NumberFormat("en-IN", {
            style: "currency",
            currency: "INR",
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        }).format(price);
    };
    const formatPercentage = (percentage) => {
        return `${percentage >= 0 ? "+" : ""}${percentage.toFixed(2)}%`;
    };
    const LoadingSkeleton = () => (_jsx("div", { className: "grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3", children: Array.from({ length: 6 }).map((_, index) => (_jsxs(Card, { className: "bg-white/10 border-white/20 backdrop-blur-sm", children: [_jsx(CardHeader, { className: "pb-4", children: _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(Skeleton, { className: "w-12 h-12 rounded-full bg-white/20" }), _jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "w-24 h-4 bg-white/20" }), _jsx(Skeleton, { className: "w-16 h-3 bg-white/20" })] })] }) }), _jsxs(CardContent, { className: "pt-0", children: [_jsx(Skeleton, { className: "w-32 h-6 mb-2 bg-white/20" }), _jsx(Skeleton, { className: "w-20 h-4 bg-white/20" })] })] }, index))) }));
    if (loading) {
        return (_jsxs("section", { id: "trending", className: "relative py-20 overflow-hidden bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900", children: [_jsx("div", { className: "absolute inset-0 bg-[radial-gradient(circle_at_20%_50%,rgba(120,119,198,0.15),transparent_50%)]" }), _jsx("div", { className: "absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(255,119,198,0.15),transparent_50%)]" }), _jsxs("div", { className: "container relative z-10 px-4 mx-auto", children: [_jsxs("div", { className: "mb-16 text-center", children: [_jsxs(Badge, { variant: "outline", className: "mb-4 text-white bg-white/10 border-white/20", children: [_jsx(RefreshCw, { className: "w-3 h-3 mr-1 animate-spin" }), "Loading"] }), _jsx("h2", { className: "mb-4 text-4xl font-bold text-white md:text-5xl", children: "Trending Cryptos" }), _jsx("p", { className: "text-xl text-gray-400", children: "Fetching the latest cryptocurrency data..." })] }), _jsx(LoadingSkeleton, {})] })] }));
    }
    if (error) {
        return (_jsx("section", { id: "trending", className: "py-20 bg-gradient-to-br from-slate-900 via-red-900 to-slate-900", children: _jsx("div", { className: "container px-4 mx-auto", children: _jsx("div", { className: "max-w-2xl mx-auto text-center", children: _jsx(Alert, { className: "bg-red-500/10 border-red-500/20", children: _jsx(AlertDescription, { className: "text-lg text-red-400", children: error }) }) }) }) }));
    }
    return (_jsxs("section", { id: "trending", className: "relative py-20 overflow-hidden bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900", children: [_jsx("div", { className: "absolute inset-0 bg-[radial-gradient(circle_at_20%_50%,rgba(120,119,198,0.15),transparent_50%)]" }), _jsx("div", { className: "absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(255,119,198,0.15),transparent_50%)]" }), _jsx("div", { className: "absolute w-2 h-2 bg-purple-400 rounded-full top-10 left-10 animate-pulse" }), _jsx("div", { className: "absolute w-3 h-3 delay-1000 bg-pink-400 rounded-full top-1/3 right-20 animate-pulse" }), _jsx("div", { className: "absolute w-2 h-2 delay-500 bg-blue-400 rounded-full bottom-20 left-1/4 animate-pulse" }), _jsxs("div", { className: "container relative z-10 px-4 mx-auto", children: [_jsxs("div", { className: "mb-16 text-center", children: [_jsxs(Badge, { variant: "outline", className: "mb-4 text-white bg-white/10 border-white/20 group", children: [_jsx(Sparkles, { className: "w-3 h-3 mr-1 group-hover:animate-spin" }), "Live Data"] }), _jsx("h2", { className: "mb-4 text-4xl font-bold text-transparent text-white md:text-5xl bg-gradient-to-r from-white via-purple-200 to-pink-200 bg-clip-text", children: "Trending Cryptos" }), _jsx("p", { className: "max-w-3xl mx-auto text-xl text-gray-400", children: "Stay ahead with real-time insights on the most promising digital assets" })] }), _jsx("div", { className: "grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3", children: trendingCoins.map((crypto, index) => {
                            const isPositive = crypto.price_change_percentage_24h >= 0;
                            const trendColor = isPositive ? "text-green-400" : "text-red-400";
                            const trendBg = isPositive ? "bg-green-500/20" : "bg-red-500/20";
                            const TrendIcon = isPositive ? TrendingUp : TrendingDown;
                            const ArrowIcon = isPositive ? ArrowUpRight : ArrowDownRight;
                            return (_jsx(Link, { to: `/coins/${crypto.name}`, className: "block group", children: _jsxs(Card, { className: "h-full overflow-hidden transition-all duration-500 bg-white/10 border-white/20 backdrop-blur-sm hover:bg-white/20 hover:border-white/30 hover:scale-105 hover:shadow-2xl hover:shadow-purple-500/25", children: [_jsx(CardHeader, { className: "pb-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-12 h-12 p-1 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20", children: _jsx("img", { src: crypto.image, alt: crypto.name, className: "object-contain w-full h-full rounded-full", onError: (e) => {
                                                                                e.currentTarget.src = `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40"><rect width="40" height="40" fill="%23374151"/><text x="20" y="25" text-anchor="middle" fill="%23fff" font-size="16">${crypto.symbol.charAt(0)}</text></svg>`;
                                                                            } }) }), _jsx("div", { className: "absolute -bottom-1 -right-1", children: _jsx("div", { className: `w-4 h-4 rounded-full ${trendBg} flex items-center justify-center`, children: _jsx(TrendIcon, { className: `w-2.5 h-2.5 ${trendColor}` }) }) })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-white transition-all duration-300 group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:from-purple-200 group-hover:to-pink-200 group-hover:bg-clip-text", children: crypto.name }), _jsx(Badge, { variant: "outline", className: "text-xs text-gray-300 bg-white/10 border-white/20", children: crypto.symbol.toUpperCase() })] })] }), _jsx(ArrowIcon, { className: "w-5 h-5 transition-all duration-300 text-white/50 group-hover:text-white group-hover:scale-110" })] }) }), _jsx(CardContent, { className: "pt-0", children: _jsxs("div", { className: "space-y-3", children: [_jsx("div", { children: _jsx("p", { className: "text-2xl font-bold text-white", children: formatPrice(crypto.current_price) }) }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-400", children: "24h Change" }), _jsx("div", { className: `flex items-center space-x-1 px-2 py-1 rounded-full ${trendBg}`, children: _jsx("span", { className: `text-sm font-semibold ${trendColor}`, children: formatPercentage(crypto.price_change_percentage_24h) }) })] })] }) })] }) }, index));
                        }) }), _jsxs("div", { className: "mt-16 text-center", children: [_jsx("p", { className: "mb-6 text-gray-400", children: "Want to explore more cryptocurrencies?" }), _jsx("button", { className: "px-8 py-3 font-semibold text-white transition-all duration-300 rounded-full shadow-lg bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 hover:scale-105 hover:shadow-purple-500/25", children: "View All Coins" })] })] })] }));
};
export default TrendingCryptos;
